// <auto-generated />
using System;
using LaneClarkAndPeacockTechnical;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaneClarkAndPeacockTechnical.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220201120009_RemoveClientNote")]
    partial class RemoveClientNote
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("LaneClarkAndPeacockTechnical.ClientDetails", b =>
                {
                    b.Property<Guid>("ClientDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientDetailsId")
                        .HasName("ClientDetailsId");

                    b.ToTable("ClientDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
